model_cfg:
  model:
    params:
      alpha: 0.5
      freeze_all: true
      losses: []

training:
  wandb_base_run_name: "cac_feat_score"
  num_epochs: 1
  force_eval_mode: true

paths:
  checkpoint: checkpoints/ood_baseline_proto_segnet_20251213_052614_val-OoDAUPR_epoch_0.7577.pth