seed: 42

wandb:
  project: "ML4CV_ASS"

model:
  encoder_name: "efficientnet_b2"
  d: 64
  stride: 8

training:
  img_height: 576 
  img_width: 1024 
  num_epochs: 30 
  evaluation_rate: 2
  batch_size: 6
  lr: 0.0004
  wd: 0.0001

losses:
  prototypical_triplet:
    anchors_magnitude: 10
    global: 1.5
    local: 0.5
  focal:
    alpha: 1
    gamma: 2

paths:
  train_path: "ml4cv_assignment/data/datasets/train"
  test_path: "ml4cv_assignment/data/datasets/test"
  save_path: "ml4cv_assignment/saved/models"
  logs_path: "ml4cv_assignment/saved/logs"
  coco_path: "ml3cv_assignment/data/datasets/coco"