training:
  wandb_base_run_name: "fpn_no_dilation"

model_cfg:
  model:
    params:
      encoder:
        type: timm
        params:
          model_name: "efficientnet_b2"
          features_only: true
          pretrained: true 
          out_indices: [1, 2, 3, 4]
          output_stride: 32 
          drop_path_rate: 0.1
      decoder:
        type: FPNDecoder
        params:
          fpn_channels: [24, 48, 120, 352]
          decoder_channels: 64
          num_classes: 13
          input_size: [360, 640]
          output_stride: 32 
          use_aspp: false