seed: 42

dataset_config:
  type: cityscapes 

model_cfg:
  use_preprocessor: false 
  model:
    type: ProtoSegNet
    params:
      decoder:
        params:
          num_classes: 19
          input_size: [512, 1024]
      num_classes: 19
      losses:
        - type: DiceLoss
          params:
            average: "macro"
            ignore_index: 255
        - type: PrototypicalGlobalLocalTripletLoss
          params:
            margin_global: 1.5
            margin_local: 0.5
            magnitude: 10
            num_classes: 19
            ignore_index: 255
  ckpt_remap:
    fam_blocks: "fusion_blocks"

training:
  wandb_base_run_name: "cityscapes_closed_ptl"
  batch_size: 8

  train_transforms:
    type: Compose
    params:
      transforms:
        - type: OneOf
          params:
            p: 1.0
            transforms:
              # Global context
              - type: Resize
                params:
                  height: 512
                  width: 1024
                  p: 1.0

              # Zoom & Crop -> Scale invariance
              - type: RandomResizedCrop
                params:
                  size: [512, 1024]
                  scale: [0.2, 1.0] 
                  ratio: [1.5, 2.0] 
                  p: 1.0
      
        # Geometric augmentations
        - type: HorizontalFlip
          params:
            p: 0.5

        # Color augmentations
        # Simulate different lightning conditions and weather scenarios
        - type: ColorJitter
          params:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.1
            p: 0.5
              
        # Weather augmentations
        # Simulate harsh environmental conditions
        - type: OneOf
          params:
            transforms:
              - type: RandomShadow 
                params:
                  p: 1.0
              - type: RandomSunFlare
                params:
                  p: 1.0
              - type: RandomRain
                params:
                  p: 1.0
            p: 0.2

          # Normalization & tensor conversion
        - type: Normalize
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            max_pixel_value: 255.0
            p: 1.0
        - type: ToTensorV2
          params: 
            p: 1.0

  val_transforms:
    type: Compose
    params:
      transforms:
        - type: LongestMaxSize 
          params:
            max_size: 1024
        - type: Normalize
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            max_pixel_value: 255.0
            p: 1.0
        - type: ToTensorV2
          params: 
            p: 1.0
  
  metrics:
    - type: MeanIoU
      params:
        num_classes: 19
        per_class: true
        ignore_index: 255 

  callbacks:
    - type: EarlyStoppingCallback
      params:
        patience: 10
        minimize: false
        history_key: val/mIoU_epoch
    - type: ModelSavingCallback
      params:
        out_dir: checkpoints  
        minimize: false
        history_key: val/mIoU_epoch
    - type: VisualizeSegmentationResultsCallback
      params:
        num_samples: 8
        dataset_type: cityscapes
    - type: ModelSummaryCallback
      params: {}
    - type: PixelEmbeddingsCallback
      params:
        anchors_magnitude: 10
        min_num_pixels: 1000
        dataset_type: cityscapes

paths:
  cityscapes_root_dir: datasets/cityscapes
  checkpoint: checkpoints/ptl_dice_20251206_235304_val-mIoU_epoch_0.6933.pth