seed: 42

dataset_config:
  type: streethazards
  add_anomalies: false 
  mask_shift: true

model_cfg:
  use_preprocessor: false 
  model:
    type: ProtoSegNet
    params:
      encoder_lr: 1e-4
      decoder_lr: 1e-3
      encoder_weight_decay: 0.00001
      decoder_weight_decay: 0.05
      num_classes: 13
      T: 1.0
      alpha: 0.5
      xi: 5.0
      anchors_magnitude: 10.0
      use_running_centers: false 
      centers_momentum: 0.9
      losses:
        - type: DiceLoss
          params:
            average: "macro"
            ignore_index: 254
        - type: PrototypicalGlobalLocalTripletLoss
          params:
            margin_global: 1.5
            margin_local: 0.5
            magnitude: 10
            num_classes: 13
            ignore_index: 254
  ckpt_remap:
    fam_blocks: "fusion_blocks"

training:
  wandb_project_name: ml4cv_assignment
  wandb_entity: aarcara
  batch_size: 16
  num_epochs: 100
  evaluation_rate: 1
  use_mixed_precision: true 
  use_torch_compile: false 
  num_workers: 8
  
  val_transforms:
    type: Compose
    params:
      transforms:
        - type: LongestMaxSize 
          params:
            max_size: 640
        - type: Normalize
          params:
            mean: [0.331, 0.346, 0.373]
            std: [0.162, 0.160, 0.174]
            max_pixel_value: 255.0
            p: 1.0
        - type: ToTensorV2
          params: 
            p: 1.0

  metrics:
    - type: MeanIoU
      params:
        num_classes: 13
        per_class: true
        ignore_index: 254

  callbacks:
    - type: EarlyStoppingCallback
      params:
        patience: 10
        minimize: false
        history_key: val/mIoU_epoch
    - type: ModelSavingCallback
      params:
        out_dir: checkpoints  
        minimize: false
        history_key: val/mIoU_epoch
    - type: VisualizeSegmentationResultsCallback
      params:
        num_samples: 8
    - type: ModelSummaryCallback
      params: {}
    - type: PixelEmbeddingsCallback
      params:
        anchors_magnitude: 10
        min_num_pixels: 1000

paths:
  street_hazards_train_dir: datasets/train
  street_hazards_test_dir: datasets/test
  coco_data_dir: datasets/coco