dataset_config:
  type: streethazards
  add_anomalies: true
  prob_insert: 1.0

model_cfg:
  model:
    type: ProtoSegNet
    params:
      encoder_lr: 1e-5
      decoder_lr: 1e-4
      losses:
        - type: DiceLoss
          params:
            average: "macro"
            ignore_index: 13
        - type: PrototypicalGlobalLocalTripletLoss
          params:
            margin_global: 1.5
            margin_local: 0.5
            magnitude: 10
            num_classes: 13
            ignore_index: 13
        - type: ObjectosphereLoss
          params:
            xi: 5.0
            unknown_label: 13

training:
  wandb_base_run_name: "ood_baseline_proto_segnet"
  train_transforms:
    type: Compose
    params:
      transforms:
        - type: LongestMaxSize 
          params:
            max_size: 640
        - type: Normalize
          params:
            mean: [0.331, 0.346, 0.373]
            std: [0.162, 0.160, 0.174]
            max_pixel_value: 255.0
            p: 1.0
        - type: ToTensorV2
          params: 
            p: 1.0

  metrics:
    - type: MeanIoU
      params:
        num_classes: 13
        per_class: true
        ignore_index: 13
    - type: AUPR
      params:
        unknown_label: 13

  callbacks:
    - type: EarlyStoppingCallback
      params:
        patience: 10
        minimize: false
        history_key: val/OoDAUPR_epoch
    - type: ModelSavingCallback
      params:
        out_dir: checkpoints  
        minimize: false
        history_key: val/OoDAUPR_epoch
    - type: VisualizeSegmentationResultsCallback
      params:
        num_samples: 8
    - type: ModelSummaryCallback
      params: {}
    - type: PixelEmbeddingsCallback
      params:
        anchors_magnitude: 10
        min_num_pixels: 1000

paths:
  checkpoint: checkpoints/proto_segnet_efficientnet_b2_encoder_20251127_214917_val-mIoU_epoch_0.6772.pth