training:
  wandb_base_run_name: "ptl_focal"

model_cfg:
  model:
    params:
      losses:
        - type: PrototypicalGlobalLocalTripletLoss
          params:
            margin_global: 1.5
            margin_local: 0.5
            magnitude: 10
            num_classes: 13
            ignore_index: 254
        - type: FocalLoss
          params:
            alpha: 1.0
            gamma: 2.0
            reduction: "mean"
            ignore_index: 254